matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"

language: cpp

env:
  - CXX=g++-7

script: make all
